Repository Team-3-2/WHYNE, pull requests merged in 2025-10, with the labels that each got.

#55 [#38] taste 컴포넌트 리팩토링
  src/app/example/page.tsx
  src/components/index.ts
  src/components/taste/detail-taste.stories.tsx
  src/components/taste/review-taste.stories.tsx
  src/components/taste/review-taste.tsx
  src/components/wine-taste/_components/detail-taste-item.tsx
  src/components/wine-taste/_components/review-taste-item.tsx
  src/components/wine-taste/_types/index.ts
  src/components/wine-taste/_utils/tasteUtils.ts
  src/components/wine-taste/index.ts
  src/components/wine-taste/wine-taste.stories.tsx
  src/components/wine-taste/wine-taste.tsx
Labels: 🎨 Design, 🫟 chromatic

#56 [#48] 랜딩페이지 리팩토링 작업
  src/app/(landing)/_components/landing-banner.tsx
  src/app/(landing)/_components/landing-section.tsx
  src/app/(landing)/_constants/sections.ts
  src/app/(landing)/_types/index.ts
  src/app/layout.tsx
  src/app/page.tsx
Labels: 🔨 Refactor

#70 [#8] 모달 표출시 스크롤 방지 로직 변경
  src/components/modal/confirm-modal.tsx
  src/lib/utils.ts
Labels: 🔨 Refactor

#72 [#65] 버튼 컴포넌트 개선
  src/components/button/Button.stories.tsx
  src/components/button/arrow-button.tsx
  src/components/button/basic-button.tsx
  src/components/button/carousel-nav-button.tsx
  src/components/button/icon-button.tsx
  src/components/index.ts
  src/components/wine-recommend/wine-recommend.tsx
Labels: ✨ Feature, 🔨 Refactor

#82 [#81] 리뷰 등록 모달 관련 작업 및 리뷰 등록 로직 일부분 작업
  Icon 
  src/api/reviews/post-review.ts
  src/app/wines/[id]/_components/review-form.tsx
  src/app/wines/[id]/_components/wine-info.tsx
  src/app/wines/[id]/_hooks/use-review-submit.ts
  src/app/wines/[id]/_types/index.ts
  src/app/wines/[id]/page.tsx
Labels: ✨ Feature, 🎨 Design, 📬 API

#88 [#] 버셀 에러 수정
  src/components/wine-recommend/elements/wine-card-recommend.tsx
  src/components/wine-recommend/wine-recommend.tsx
Labels: 🐞 BugFix

#89 [#x] 리뷰 등록 axios 수정
  src/api/reviews/post-review.ts
Labels: 📬 API

#90 [#x] 스토리북 예시 파일 삭제
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: 📃 Docs

#84 [#76] 아이콘 컴포넌트 정적/동적 import 방식 개선
  src/app/globals.css
  src/components/button/Button.stories.tsx
  src/components/button/basic-button.tsx
  src/components/button/carousel-nav-button.tsx
  src/components/button/icon-button.tsx
  src/components/button/like-button.tsx
  src/components/icon/icon-map.ts
  src/components/icon/icon.stories.tsx
  src/components/icon/icon.tsx
  src/components/icon/static-icon-map.ts
  src/components/index.ts
  src/components/text-input/text-input.tsx
Labels: 🐞 BugFix, 🔨 Refactor

#92 [#86] 버튼 컴포넌트 최최최종 수정(명칭 개선)
  src/app/(auth)/login/page.tsx
  src/components/button/Button.stories.tsx
  src/components/button/basic-button.tsx
  src/components/button/like-button.tsx
  src/components/modal/confirm-modal.tsx
Labels: 🔨 Refactor

#80 [#69] 카드 컴포넌트 추가 개선
  next.config.ts
  public/images/placeholder/img-wine.svg
  src/app/example/page.tsx
  src/components/card/card-action-menu.tsx
  src/components/card/card-img.tsx
  src/components/card/card-info.tsx
  src/components/card/card-review.tsx
  src/components/card/card.stories.tsx
  src/components/card/card.tsx
  src/constants/base64-images.ts
  src/mock.ts
Labels: ✨ Feature, 🔨 Refactor

#98 [#95] GNB 로그인, 비로그인 로직 구현
  src/app/(auth)/login/page.tsx
  src/app/myprofile/_components/profile-tabs/profile-tabs.tsx
  src/components/gnb/gnb.tsx
  src/hooks/use-logout.ts
  src/types/user-type.ts
Labels: ✨ Feature, 🎨 Design

#100 [#85] 별점 컴포넌트 기능 추가
  src/app/example/page.tsx
  src/app/globals.css
  src/app/myprofile/_components/review-item/review-rating.tsx
  src/app/wines/[id]/_components/review-form.tsx
  src/components/card/card-info.tsx
  src/components/index.ts
  src/components/rating/fill-shape.tsx
  src/components/rating/rating-bar-item.tsx
  src/components/rating/rating-distribution.tsx
  src/components/rating/rating-input.tsx
  src/components/rating/rating.stories.tsx
  src/components/rating/rating.tsx
  src/components/rating/style.ts
  src/components/star-rating/scorebar.tsx
  src/components/star-rating/star-rating.tsx
  src/components/star-rating/star.tsx
Labels: ✨ Feature, 🔨 Refactor

#101 [#99] 임시 로더 추가
  src/app/myprofile/page.tsx
  src/components/loader/loader.stories.tsx
  src/components/loader/loader.tsx
Labels: ✨ Feature, 🎨 Design

#104 [#103] zustand를 사용한 유저 정보 관리
  package-lock.json
  package.json
  src/api/auth/login.ts
  src/app/(auth)/_components/form-wrapper.tsx
  src/app/(auth)/login/page.tsx
  src/components/gnb/gnb.tsx
  src/lib/axios.ts
  src/store/user-store.ts
Labels: 🔨 Refactor
