Repository Team-3-2/WHYNE, pull requests merged in 2025-09, with the labels that each got.

#12 #x 전체 코드 싱글쿼트 수정
  .storybook/main.ts
  .storybook/preview.ts
  src/app/fonts.ts
  src/app/layout.tsx
  src/lib/utils.ts
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  tailwind.config.ts
Labels: 🐞 BugFix

#14 #x storybook 배포 및 깃허브 액션 설정
  .github/workflows/chromatic.yml
  .gitignore
  package-lock.json
  package.json
Labels: 🌏 Deploy

#15 Update README.md
  README.md
Labels: 📃 Docs

#20 #5 Taste 공통 컴포넌트 개발
  src/components/gauge/block-gauge.stories.tsx
  src/components/gauge/block-gauge.tsx
  src/components/taste/Taste.stories.tsx
  src/components/taste/Taste.tsx
  tailwind.config.ts
Labels: 🎨 Design

#27 [#6] 아이콘 컴포넌트 컬러 변수 수정
  src/components/icon/Icon.tsx
Labels: 🐞 BugFix

#28 [#8] 텍스트 인풋 컴포넌트 제작
  src/app/example/page.tsx
  src/components/index.ts
  src/components/select-type/select-type.tsx
  src/components/text-input/text-input.stories.tsx
  src/components/text-input/text-input.tsx
Labels: 🎨 Design

#29 [#5] taste 컴포넌트 세분화
  src/components/index.ts
  src/components/taste/Taste.stories.tsx
  src/components/taste/Taste.tsx
  src/components/taste/detail-taste.stories.tsx
  src/components/taste/detail-taste.tsx
  src/components/taste/review-taste.stories.tsx
  src/components/taste/review-taste.tsx
Labels: 🎨 Design

#31 [#4] 마이페이지 레이아웃 생성
  src/app/myprofile/_components/index.ts
  src/app/myprofile/_components/my-profile/MyProfile.tsx
  src/app/myprofile/_components/profile-sidebar/ProfileSidebar.stories.tsx
  src/app/myprofile/_components/profile-sidebar/ProfileSidebar.tsx
  src/app/myprofile/_components/profile-tabs/ProfileTabs.stories.tsx
  src/app/myprofile/_components/profile-tabs/ProfileTabs.tsx
  src/app/myprofile/page.tsx
  src/components/flavor/Flavor.tsx
  src/components/gnb/Gnb.tsx
  tsconfig.json
Labels: 🎨 Design

#32 [#4] 마이페이지 내가 쓴 후기 아이템 구현
  public/images/test/test_wine.png
  src/app/myprofile/_components/index.ts
  src/app/myprofile/_components/my-profile/MyProfile.tsx
  src/app/myprofile/_components/review-item/ReviewInfo.tsx
  src/app/myprofile/_components/review-item/ReviewItem.stories.tsx
  src/app/myprofile/_components/review-item/ReviewItem.tsx
  src/app/myprofile/_components/review-item/ReviewRating.tsx
  src/components/dropdown-menu/DropdownMenu.tsx
Labels: 🎨 Design

#39 [#35] 컴포넌트 네이밍 변경
  .github/ISSUE_TEMPLATE/🐞-버그-리포트-템플릿.md
  src/app/myprofile/_components/index.ts
  src/app/myprofile/_components/my-profile/my-profile.tsx
  src/app/myprofile/_components/profile-sidebar/profile-sidebar.stories.tsx
  src/app/myprofile/_components/profile-sidebar/profile-sidebar.tsx
  src/app/myprofile/_components/profile-tabs/profile-tabs.stories.tsx
  src/app/myprofile/_components/profile-tabs/profile-tabs.tsx
  src/app/myprofile/_components/review-item/review-info.tsx
  src/app/myprofile/_components/review-item/review-item.stories.tsx
  src/app/myprofile/_components/review-item/review-item.tsx
  src/app/myprofile/_components/review-item/review-rating.tsx
  src/components/chip/chip.stories.tsx
  src/components/chip/chip.tsx
  src/components/dropdown-menu/dropdown-menu.stories.tsx
  src/components/dropdown-menu/dropdown-menu.tsx
  src/components/flavor/flavor.stories.tsx
  src/components/flavor/flavor.tsx
  src/components/gnb/gnb.stories.tsx
  src/components/gnb/gnb.tsx
  src/components/header/header.stories.tsx
  src/components/header/header.tsx
  src/components/index.ts
Labels: 🐞 BugFix

#40 [#34] 아이콘 컴포넌트 리팩토링
  src/components/icon/icon.stories.tsx
  src/components/icon/icon.tsx
  src/components/index.ts
  src/components/text-input/text-input.tsx
  tailwind.config.ts
Labels: 🐞 BugFix, 🔨 Refactor

#33 [#9] 버튼 컴포넌트 구현
  .github/ISSUE_TEMPLATE/🐞-버그-리포트-템플릿.md
  src/components/button/Button.stories.tsx
  src/components/button/arrow-button.tsx
  src/components/button/basic-button.tsx
  src/components/button/icon-button.tsx
  src/components/button/style.ts
  src/components/icon/icon-map.ts
  src/components/index.ts
  src/components/select-type/select-type.tsx
Labels: 🎨 Design

#41 [#8] 프로필 컴포넌트 제작
  .github/ISSUE_TEMPLATE/🐞-버그-리포트-템플릿.md
  next.config.ts
  public/images/profile/default-profile.svg
  src/app/example/page.tsx
  src/components/index.ts
  src/components/profile/profile.stories.tsx
  src/components/profile/profile.tsx
Labels: 🎨 Design

#44 [#16] 리뷰 평점(별점) 컴포넌트 구현
  src/components/icon/icon.tsx
  src/components/index.ts
  src/components/star-rating/rating-breakdown.tsx
  src/components/star-rating/scorebar.tsx
  src/components/star-rating/star-rating.stories.tsx
  src/components/star-rating/star-rating.tsx
  src/components/star-rating/star.tsx
  tailwind.config.ts
Labels: 🎨 Design

#46 [#8] 검색 컴포넌트 제작
  src/app/example/page.tsx
  src/components/searchbar/searchbar.stories.tsx
  src/components/searchbar/searchbar.tsx
Labels: 🎨 Design

#47 [#x] Chromatic 라벨 기반 실행 테스트
  .github/workflows/chromatic.yml
Labels: 🌏 Deploy, chromatic

#53 Feature/recommand-> 뼈대 제작 + 목.ts
  src/components/wine-recommend/elements/wine-card-recommend.tsx
  src/components/wine-recommend/wine-recommend.tsx
  src/mock.ts
  tailwind.config.ts
Labels: ✨ Feature
